# Generated by Django 2.2.7 on 2019-11-18 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawl',
            name='CONTENT',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='crawl',
            name='DATE',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='crawl',
            name='IMG',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='crawl',
            name='NAME',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
