# Generated by Django 2.2.7 on 2019-11-20 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0003_crawl_pre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawl',
            name='LABEL',
            field=models.IntegerField(null=True),
        ),
    ]
