# Generated by Django 2.2.7 on 2019-11-28 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0004_auto_20191120_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawl',
            name='V',
            field=models.TextField(null=True),
        ),
    ]
