# Generated by Django 2.2.7 on 2019-12-04 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0005_crawl_v'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crawl',
            name='V',
        ),
    ]
